### ISSUE TITLE
Clarify the number of finalists in track events

### ISSUE THREAD

**Issue by rdunlop** [iuf/rulebook#117]
Given that the overall track champion is derived from multiple events it should be clearer how many finalists are recommended/allowed for all of the events:

Section 2.1.4

"The number of finalists will be the same as the number of usable lanes on the track. The same number of finalists applies for finals that don’t use lanes. Finals are composed regardless of age group, but male and female competitors are in separate finals."

Proposed change in meanining:
- We should only allow the number of finalists in any of the track events to be the maximum number of finalists than ANY of the events can have. Ie: if we can only run 6 finalists in the 800m due to physical track constraints, then we should only run 6 finalists in ANY of the track events...even if we could run 8 finalists in the 100m.

**Comment by scotthue** [comment]
In rulebook now.
