### ISSUE TITLE
Muni minimum requirements for DH & XC tracks

### ISSUE THREAD

**Issue by schocco** [iuf/rulebook#129]
Not all offroad courses are suitable for XC or downhill races.
Using the muni difficulty ratings, minimum standards for XC and DH can be established.

The overall score of the UDH and UXC ratings could be used to set lower and upper bounds to distinguish between beginner and advanced courses.
Anything that is below the lower bounds is simply not suited for a DH / XC race and must be called differently..

**Comment by scotthue** [comment]
Currently implemented in the rulebook.
